config/routes.rb
Rails.application.routes.draw do
  root 'static#about'
  resources :bookings
  resources :wish_list_cars
  resources :reviews
  resources :owned_cars
  resources :car_models
  resources :users
  get "/static/about", to: "static#about", as: 'about'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/car_models/inventory/:id' => 'car_models#inventory', as: 'inventory'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wish_list_car.rb
class WishListCar < ApplicationRecord
  belongs_to :user
  belongs_to :car_model

  validates :user_id, presence: true
  validates :car_model_id, presence: true

  validate :already_exist?

  def already_exist?
    if WishListCar.find_by(user_id: self.user_id, car_model_id: self.car_model_id)
      errors.add(:car_model_id, "You have already requested this car")
    end
  end

end

app/controllers/wish_list_cars_controller.rb
class WishListCarsController < ApplicationController

  def index
    return head(:forbidden) unless is_admin?
    @wish_list_cars = WishListCar.all
  end

  def show
    return head(:forbidden) unless is_admin?
    @wish_list_car = WishListCar.find(params[:id])
  end

  def new
    @wish_list_car = WishListCar.new
  end

  def create
    @wish_list_car = WishListCar.new(wish_list_car_params)
    if @wish_list_car.valid?
        @wish_list_car.save
        redirect_to current_user
    else
        render :new
    end
  end

  def edit
    @wish_list_car = WishListCar.find(params[:id])
    return head(:forbidden) unless has_access(@wish_list_car.user_id)
  end

  def update
    @wish_list_car = WishListCar.find_by(id: params[:id])
    @wish_list_car.update(wish_list_car_params)
    redirect_to @wish_list_car
  end

  def destroy
    @wish_list_car = WishListCar.find_by(id: params[:id])
    return head(:forbidden) unless has_access(@wish_list_car.user_id)
    @wish_list_car.destroy
    redirect_to @wish_list_car
  end


  private

  def wish_list_car_params
    params.require(:wish_list_car).permit(:car_model_id, :user_id)
  end

end

app/helpers/wish_list_cars_helper.rb
module WishListCarsHelper
end

app/views/wish_list_cars/_form.html.erb
<% if @wish_list_car.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@wish_list_car.errors.count, "error") %>
      prohibited this wish from being created:
    </h2>

    <ul>
    <% @wish_list_car.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @wish_list_car do |f| %>

  <%= f.label :car_model_id %>
  <%= f.collection_select :car_model_id, CarModel.all, :id, :car_name %>
  <%= f.hidden_field :user_id, value: session[:user_id] %>
  <%= f.submit %>
<% end %>

app/views/wish_list_cars/edit.html.erb
<h1>Edit<h1>

<%= render "form" %>

app/views/wish_list_cars/index.html.erb
<h1>Index for Wish List Cars</h1>

<ul>
    <% @wish_list_cars.each do |wish_list_car| %>
    <li>
     <%= link_to wish_list_car.car_model.car_name, wish_list_car %>
    </li>
    <br>
    <% end %>
</ul>
<%= button_to "Create Wish List Car", new_wish_list_car_path, :method => :get  %>

app/views/wish_list_cars/show.html.erb
<h1>Show Wish list Car</h1>

<%= @wish_list_car.car_model.car_name  %><br>
<%= @wish_list_car.user.name %><br>
<br>
<%= button_to "Edit wish_list_car", edit_wish_list_car_path(@wish_list_car), method: :get %>
<%= button_to "Delete this wish_list_car", @wish_list_car, :method => :delete  %>