config/routes.rb
Rails.application.routes.draw do
  root 'static#about'
  resources :bookings
  resources :wish_list_cars
  resources :reviews
  resources :owned_cars
  resources :car_models
  resources :users
  get "/static/about", to: "static#about", as: 'about'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/car_models/inventory/:id' => 'car_models#inventory', as: 'inventory'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :wish_list_cars
  has_many :bookings
  has_many :reviews
  has_many :owned_cars
  has_many :rentals, through: :bookings, source: :owned_car
  has_many :car_models, through: :wish_list_cars

  validates :name, presence: true

  validates :password_digest, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  validates :age, numericality: {greater_than: 0, allow_nil: true}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return head(:forbidden) unless is_admin?
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    return head(:forbidden) unless has_access(@user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
        session[:user_id] = @user.id
        redirect_to @user
    else
        render :new
    end
  end

  def edit
    return head(:forbidden) unless has_access(params[:id].to_i)
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    return head(:forbidden) unless has_access(params[:id].to_i)
    User.find(params[:id]).destroy
    redirect_to "/"
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :driver_id, :address, :email, :password, :password_confirmation)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being created:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :age%>
  <%= f.number_field :age %><br>
  <br>
  <%= f.label :driver_license %>
  <%= f.number_field :driver_id %><br>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %><br>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <br>
  Password: <%= f.password_field :password %><br>
  Password Confirmation: <%= f.password_field :password_confirmation %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Account Information</h2>

<%= render "form" %>

app/views/users/index.html.erb
<h1>User Index</h1>

<ul>
<% @users.each do |user| %>
  <li><%= link_to user.name, user %>
<% end %>
</ul>
<%= button_to "Create User", new_user_path, :method => :get  %>

app/views/users/new.html.erb
<h2>Create a new Account</h2>

<div class="form">
  <%= render "form" %>
</div>

app/views/users/show.html.erb
<h1 align="center">Profile:
<br><%= @user.name %> </h1>
<div class="pad-left">
  <b>Age: </b><%= @user.age %><br>
  <br>
  <b>Driver ID: </b><%= @user.driver_id %><br>
  <br>
  <b>Address: </b><%= @user.address %><br>
  <br>
  <b>Email: </b><%= @user.email %><br>
  <br>
  <b>Owned Cars: </b>
  <ul>
  <% @user.owned_cars.each do |car| %>
    <li><%= car.car_full_name %>
      <ul>
        <button><%= button_to "Edit My Car", edit_owned_car_path(car), method: :get %></button>
        <button><%= button_to "Remove Car from Inventory", car, method: :delete, data: { confirm:'Are you sure you want to remove this car? This action cannot be reversed!' } %></button>
      </ul>
    </li>
  <% end %>
  </ul>
  <%= button_to "Add my car to EV Share App Inventory!", new_owned_car_path, method: :get %>
  <br>
  <b>Requested EV Share App Cars:</b>
  <ul>
  <% @user.wish_list_cars.each do |wish| %>
    <li><%= link_to wish.car_model.car_name, wish.car_model %>
  <% end %>
  </ul>
  <b>Upcoming Bookings: </b>
  <ol>
  <% @user.bookings.each do |booking| %>
    <li><%= booking.owned_car.car_full_name %>: <%= link_to booking.pickup_time, booking %>
  <% end %>
  </ol>
  <br>
  <hr>
  <div class= "container">
  <%= button_to "Edit My Account Information", edit_user_path(@user), method: :get %>
  <%= button_to "Delete My Account", @user, method: :delete, data: { confirm:'Are you sure you want to delete your account? This action cannot be reversed!' }%>
  </div>
</div>