config/routes.rb
Rails.application.routes.draw do
  root 'static#about'
  resources :bookings
  resources :wish_list_cars
  resources :reviews
  resources :owned_cars
  resources :car_models
  resources :users
  get "/static/about", to: "static#about", as: 'about'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/car_models/inventory/:id' => 'car_models#inventory', as: 'inventory'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    return head(:forbidden) unless is_admin?
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.valid?
        @review.save
        redirect_to @review
    else
        render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    return head(:forbidden) unless has_access(@review.user_id)
  end

  def update
    @review = Review.find_by(id: params[:id]) #this is an object
    @review.update(review_params)
    redirect_to @review
  end

  def destroy
    @review = Review.find_by(id: params[:id])
    return head(:forbidden) unless has_access(@review.user_id)
    @review.destroy
    redirect_to @review
  end

  private

  def review_params
    params.require(:review).permit(:booking_id, :user_id, :description, :star_rating)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@review.errors.count, "error") %>
      prohibited this user from being created:
    </h2>

    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @review do |f| %>

  <%= f.label :booking_id %>
  <%= f.collection_select :booking_id, Booking.all, :id, :id %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :star_rating %>
  <%= f.number_field :star_rating, max: 10, min: 0 %><br>
  <%= f.hidden_field :user_id, value: session[:user_id] %>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit</h1>

<%= render "form" %>

app/views/reviews/index.html.erb
<h1>Index for Reviews</h1>

<ul>
    <% @reviews.each do |review| %>
    <li>
     Star Review: <%= link_to review.star_rating, review %>
    </li>
    <br>
    <% end %>
</ul>
<%= button_to "Create Review", new_review_path, :method => :get  %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "form" %>

app/views/reviews/show.html.erb
<h1>Show Review</h1>

Booking Time: <%= @review.booking.pickup_time %> - <%= @review.booking.dropoff_time %><br>
<br>
<%= @review.booking.owned_car.car_full_name %> in <%= @review.booking.owned_car.city %><br>
<br>
<%= @review.description  %><br>
Written By: <%= @review.user.name %><br>
Rating: <%= @review.star_rating  %><br>
<br>
<%= button_to "Edit review", edit_review_path(@review), method: :get%>
<%= button_to "Delete this review", @review, :method => :delete  %>