config/routes.rb
Rails.application.routes.draw do
  root 'static#about'
  resources :bookings
  resources :wish_list_cars
  resources :reviews
  resources :owned_cars
  resources :car_models
  resources :users
  get "/static/about", to: "static#about", as: 'about'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/car_models/inventory/:id' => 'car_models#inventory', as: 'inventory'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Kufam&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;700&family=Noto+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;700&display=swap" rel="stylesheet">
    <title>EVShareApp</title>
    <style>
    html {
  background:url("https://cdn.vox-cdn.com/thumbor/BRTRNXfEn6EjaZz-Nlfd3Jh_4pc=/1400x0/filters:no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/6455053/model-s-interior.0.jpg") no-repeat center center fixed;
  -webkit-background-size:cover;
  -moz-background-size:cover;
  -o-background-size:cover;
  background-size: cover;
  }
    </style>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

body {font-family: 'Kufam', cursive;}
</style>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1 align="left">EV Share</h1>
    <hr>
    <h6 align="right"><%= link_to "Welcome", "/", class: "nav-link" %> <%= link_to "Catalog", car_models_path, class: "nav-link" %></h6>
    <% if User.all.map{|user|user.id}.any?(session[:user_id])%>
      <h6 align="right">
        <%= link_to "Account Profile (#{current_user.name})", user_path(session[:user_id]), class: "nav-link" %><br>
        <%= link_to "Log-out", logout_path, method: :post, class: "nav-link" %>
      </h6>
    <% else %>
      <p align="right"><%= link_to "Log-in", login_path, class: "nav-link" %></p>
    <% end %>
    <% if is_admin? %>
      <center><%= link_to "User Index", users_path %> <%= link_to "Booking Index", bookings_path %> <%= link_to "Owned Car Index", owned_cars_path %> <%= link_to "Wish List Index", wish_list_cars_path %> <%= link_to "Review Index", reviews_path %></center>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>